<?php

return [
    'Pro Rector' => 1,
    'Professor (Department Head)' => 2,
    'Professor' => 3,
    'Associate Professor' => 4,
    'Head of Admin & Finance' => 5,
    'Head (Education)' => 6,
    'Deputy Head (Training)' => 7,
    'Deputy Head (Finance)' => 8,
    'Section Head (Finance)' => 9,
    'Lecturer' => 10,
    'Assistant Lecturer' => 11,
    'Instructor' => 12,
    'Office Supervisor' => 13,
    'Accountant (1)' => 14,
    'Section Clerk' => 15,
    'Senior Clerk' => 16,
    'Accountant (3)' => 17,
    'Cashier (3)' => 18,
    'Junior Clerk' => 19,
    'Assistant Librarian (4)' => 20,
    'Driver (5)' => 21,
    'Case File Clerk' => 22,
    'Security Staff' => 23,
    'Wet Cleaning Staff' => 24,
    'Security Guard' => 25,
    'General Worker' => 26,
    'Cleaner' => 27,
    'Assistant Cleaner' => 28,
];
