<?php

return [
    'Pro Rector' => 'ဒုတိယပါမောက္ခချုပ်',
    'Professor (Department Head)' => 'ပါမောက္ခ (ဌာနမှူး)',
    'Professor' => 'ပါမောက္ခ',
    'Associate Professor' => 'တွဲဖက်ပါမောက္ခ',
    'Head of Admin & Finance' => 'ဌာနမူး (စီမံ/ဘဏ္ဍာ)',
    'Head (Education)' => 'ဌာနမှူး (ပညာရေး)',
    'Deputy Head (Training)' => 'ဒုတိယဌာနမူး (သင်တန်း)',
    'Deputy Head (Finance)' => 'ဒုတိယဌာနမူး (ဘဏ္ဍာ)',
    'Section Head (Finance)' => 'ဌာနခွဲမှူး (ဘဏ္ဍာ)',
    'Lecturer' => 'ကထိက',
    'Assistant Lecturer' => 'လ/ထ ကထိက',
    'Instructor' => 'နည်းပြ',
    'Office Supervisor' => 'ရုံးအုပ်',
    'Accountant (1)' => 'စာရင်းကိုင် (၁)',
    'Section Clerk' => 'ဌာနခွဲစာရေး',
    'Senior Clerk' => 'အကြီးတန်းစာရေး',
    'Accountant (3)' => 'စာရင်းကိုင်(၃)',
    'Cashier (3)' => 'ငွေကိုင်(၃)',
    'Junior Clerk' => 'အငယ်တန်းစာရေး',
    'Assistant Librarian (4)' => 'စာကြည့်တိုက် လ/ထ (၄)',
    'Driver (5)' => 'ယာဉ်မောင်း (၅)',
    'Case File Clerk' => 'အမှုတွဲထိန်း',
    'Security Staff' => 'လုံခြုံရေး',
    'Wet Cleaning Staff' => 'သန့်ရှင်းရေး(အစို)',
    'Security Guard' => 'အစောင့်',
    'General Worker' => 'လုပ်သား',
    'Cleaner' => 'သန့်ရှင်းရေး',
    'Assistant Cleaner' => 'သန့်ရှင်းရေး(အကူ)',
];
